### ISSUE TITLE
Path not mapped in remote mode

### ISSUE THREAD

**Issue by DanieleBarreca** [vatlab/SoS#1098]
When I try to run the following command

```
%run -r server
sh:
   pwd
```
I get the following error

ERROR: Failed to locate **/Users/dbarreca**/Dev/Python/.sos/interactive.sos
ERROR: Command 'ssh -q my_address -p 22 "bash --login -c '[ -d /home/dbarreca/Dev/Python ] || mkdir -p /home/dbarreca/Dev/Python; cd **/home/dbarreca**/Dev/Python && sos run **/Users/dbarreca**/Dev/Python/.sos/interactive.sos'" ' returned non-zero exit status 1.

It would seem like the home folder is not mapped when sos is launched on the remote host (it is instead mapped when copying the interactive.sos script):

```
[dbarreca@xxx .sos]$ pwd
/home/dbarreca/Dev/Python/.sos
[dbarreca@xxx .sos]$ ls -latr
total 0
drwxrwx--- 3 dbarreca xxx  1 Dec  5 07:53 ..
-rw-r--r-- 1 dbarreca xxx 33 Dec  5 08:09 interactive.sos
drwxrwx--- 2 dbarreca xxx  1 Dec  5 08:10 .
[dbarreca@xxx .sos]$ 
```

My hosts.yaml is the following:

```
hosts:
  server:
    address: "my_address"
    paths:
      home: "/home/dbarreca"
  mac:
    address: "localhost"
    paths:
      home: "/Users/dbarreca"
```
