### ISSUE TITLE
Failed to locate task engine type pbs

### ISSUE THREAD

**Issue by DanieleBarreca** [vatlab/SoS#1101]
I cannot configure a remote slurm queue. I get the error:

> Failed to locate task engine type pbs.

This is my hosts.yaml file, most likely it is some configuration/installation error.

```
hosts:
  mac:
    address: "localhost"
    paths:
      projects: "/Users/{user_name}/Dev/Python"
    shared:
      scratch: "/Volumes/scratch"
  cluster:
    address: "headnode.url"
    paths:
      projects: "/scratch/users/{user_name}/private/projects"
    shared:
      scratch: "/scratch"
    queue_type: pbs
    status_check_interval: 60
    max_running_jobs: 100
    job_template: |
      #!/bin/bash
      #SBATCH --time={walltime}
      #SBATCH --cpus-per-task={cores}
      #SBATCH --mem-per-cpu={mem_per_cpu}
      #SBATCH --partition={partition}
      #SBATCH --workdir={cur_dir}
      #SBATCH --output={cur_dir}/{task}.out
      #SBATCH --error={cur_dir}/{task}.err
      #SBATCH --job-name={task}

      mkdir -p .sos
      sos execute {task} -v {verbosity} -s {sig_mode} {'--dryrun' if run_mode == 'dryrun' else ''}
    walltime: "0-08:00:00"
    cores: 4
    mem_per_cpu: "2G"
    partition: "develop"
    submit_cmd: "sbatch {job_file}"
    submit_cmd_output: "Submitted batch job {job_id}"
    status_cmd: "squeue --job {job_id}"
    kill_cmd: "scancel {job_id}"
```

```
xxx:test_sos dbarreca$ sos remote list
Alias    Address   Queue Type Description                                                              
-----    -------   ---------- -----------                                                              
cluster  ?         ?          Failed to locate task engine type pbs. Available engine types are process
mac      localhost process          
```
