### ISSUE TITLE
Job submission walltime not consistent between tasks

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1142]
Sorry it is not MWE (hard to come up with one when remote jobs is involved), but I have this workflow:

[summary_statistics_finemapping.sos.txt](https://github.com/vatlab/SoS/files/2719086/summary_statistics_finemapping.sos.txt)

You can focus on the `task:` definition in `susie_bhat_1` step. It says `walltime = '10min'`.

Now when i run this step, I get:

```
INFO: Running susie_bhat_1: Run SuSiE bhat version
ERROR: [susie_bhat_1]: All tasks should have the same resource walltime
[susie_bhat]: 1 pending step: susie_bhat_2
```

so i changed this line

https://github.com/vatlab/SoS/blob/9199ef0c9e1fc46cb399a26453c3d5497e3ada9f/src/sos/tasks.py#L89

to 

```
f'All tasks should have the same resource {key}: {val0} is not equal to {val}')
```

I get 

```
All tasks should have the same resource walltime: 00:10:00 is not equal to None
```

The trunk_size is 5, and I have 35 (test) commands here. 

To rule out edge case I set `trunk_size = 6` but got the same error. Anything you would suggest me to try? Anything obviously wrong? The configuration file is:

```
  machine_name:
    description: xxxxx
    address: localhost
    paths:
      home: /home/{user_name}
    queue_type: pbs
    status_check_interval: 20
    account: ""
    partition: SBATCH --partition=short
    job_template: | 
      #!/bin/bash
      #{partition}
      #{account}
      #SBATCH --time={walltime}
      #SBATCH --nodes=1
      #SBATCH --ntasks-per-node=1
      #SBATCH --cpus-per-task={cores}
      #SBATCH --mem-per-cpu={mem//10**9}G
      #SBATCH --job-name={job_name}
      #SBATCH --output={job_name}.out
      #SBATCH --error={job_name}.err
      cd {cur_dir}
      module load R
      sos execute {task} -v {verbosity} -s {sig_mode}
    kill_cmd: scancel {job_id}
    max_cores: 40
    max_mem: 64G
    max_running_jobs: 60
    max_walltime: '36:00:00'
    status_cmd: squeue --job {job_id}
    submit_cmd: sbatch {job_file}
    submit_cmd_output: Submitted batch job {job_id}
```
