### ISSUE TITLE
Maximum running jobs not honored on cluster

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1149]
Previously we seem to have the issue that maximum jobs in the queue are more than the allowed maximum. Today the problem seems the other way around: SoS is still submitting jobs like this:

```
INFO: M80_ad136f1872ea7cd1 submitted to midway2 with job id 55933675
INFO: M80_68f63a036f9ccfbd submitted to midway2 with job id 55933719
INFO: M80_f8309250aece0c9d submitted to midway2 with job id 55933727
INFO: M80_bb1d60e6337803f4 submitted to midway2 with job id 55933729
INFO: M80_534d82e405ce6605 submitted to midway2 with job id 55933735
INFO: M80_c3581ff31e05cf5f submitted to midway2 with job id 55933738
...
```

a few at a time. But my queue looks like:

```
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
          55933727   broadwl M80_f830     gaow  R       3:19      1 midway2-0025
          55933738   broadwl M80_c358     gaow  R       0:39      1 midway2-0089
          55933735   broadwl M80_534d     gaow  R       1:31      1 midway2-0015

``` 

There is constantly only 2 to 3 jobs  in the queue. It makes the whole undertaking a lot slower. 

This is not what happens at the start of the run. Back then, SoS still uses about the maximum allowed slot in the queue. Only after a while it became like this. Now to get my stuff done i'd have to kill the current submission, remove all signatures and resubmit with `-s build`. 

I am wondering how SoS checks and decides to submit more? Maybe this is because there are many failed jobs (or jobs of some undetermined status) that filled up the slot? I can imaging eventually SoS will hang when these 3 remaining slots are somehow occupied. So before I kill and purge my jobs I'm happy to use my current status to help doing some diagnostics . @BoPeng please let me know what information you'd like me to extract and report.

**Comment by BoPeng** [comment]
I am checking this with a VM... Too bad that I cannot find a single machine slurm VM.

**Comment by gaow** [comment]
Oh I'm not sure how reproducible it is. There indeed many failed jobs in this batch of submission, but of course not all jobs fail. I suspect some of the jobs become "zombies" that hold the slot; that is why I was asking if you order some status check report from my end and I'll show them here.

**Comment by BoPeng** [comment]
oK. I am running a task-spooler on a ubuntu vm, with number of concurrent jobs set to 20. Everything seems to be ok so I am on the way of creating a few failed jobs.

**Comment by gaow** [comment]
Great, while you are on it, maybe change `trunk_size` to greater than 1 to reproduce #1147 . For my case i have 34K jobs, with trunk size 80. Each trunk has a few failed jobs (some patterns of edge case my code did not capture). Eventually it jammed up and now I see only one task in my queue, but still running and submitting ...

**Comment by BoPeng** [comment]
Without `trunk_size` everything seems to be ok. There are failed tasks and the running tasks are kept almost constant at capacity.

**Comment by BoPeng** [comment]
Everything seems to be ok with the following script

```
[1]
input: for_each=dict(i=range(5000))

task:  walltime='10m', trunk_size=100

print(f'this is task {i}')

import time
import random
time.sleep(random.random()*5)
fail_if(random.random() < 0.1)
```
On a VM with
```
    vm:
        address: 192.168.47.129
        paths:
            home: /home/bpeng1
        description: task spooler on a single machine
        queue_type: pbs
        status_check_interval: 5
        job_template: |
            #!/bin/bash
            cd {cur_dir}
            sos execute {task} -v {verbosity} -s {sig_mode} {'--dryrun' if run_mode == 'dryrun' else ''}
        max_running_jobs: 20
        submit_cmd: tsp -L {task} sh {job_file}
        status_cmd: tsp -s {job_id}
        kill_cmd: tsp -r {job_id}
```
with `TS_SLOTS` set to 20.

Perhaps the latest master works on your cluster as well.
