### ISSUE TITLE
Local variables in config file.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1331]
We allow

```
%save my_config.yml -f
hosts:
  host_31:
    R_version: 3.1
    task_template: |
      module load R/{R_version}
      {command}
  host_33:    
    based_on: hosts.host_31
    R_version: 3.3
```
because `R_version` will be expanded for `task_template`.

We however does not allow

```
sos run -q host_31 R_version=3.3
```
because the templates are pre-expanded so `task_template` is
```
module load R/3.1
 {command}
```
not
```
module load R/{R_version}
{command}
```
when the template is used.

It might be easier to allow the later usage and make `R_version=3.1` a default value for `R_version`.

The technical difficulty is that if we do not pre-expand `R_version`, we will need to keep it when we expand `task_template`, but currently we do not  have access to this dictionary when we expand `task_template`.
