### ISSUE TITLE
Failed to execute remote workflow using full path.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1332]
With the following configuration (note the `scratch` for remote host

```
localhost: mac_pro
hosts:
  mac_pro:
    address: localhost
    paths:
      home: /Users/bpeng1
  bcbm:
    address: bcbm-bpeng.mdanderson.edu   
    paths:
      home: /Users/bpeng1/scratch
```
The following workflow fails to execute
```
%run -r bcbm -c my_config.yml
sh:
    echo $HOSTNAME
```
because command uses full path of remote host.
```
cd /Users/bpeng1/scratch/sos/sos-docs/src/user_guide && 
sos run /Users/bpeng1/sos/sos-docs/src/user_guide/.tmp_script_uciqz8w3.sos
```
