### ISSUE TITLE
Submit the SoS job submitter to a compute node

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1407]
Similar to https://github.com/cumc/dsc/issues/5, in SoS we often have to submit a job to the cluster compute node that submits SoS tasks from there. An interface is proposed in the DSC ticket, and an implementation potentially will not need to involve SoS. But I'm opening this ticket just in case it is something better solved at SoS level.

**Comment by pgcudahy** [comment]
I'd like to add that the login nodes at my cluster are often congested, so the SoS job submitter runs *very* slowly. Forwarding the job submitter to a compute node would likely considerably speed up my runs and not annoy my fellow users.

**Comment by BoPeng** [comment]
For this particular request, what you want to do was

1. execute a workflow on a computing node (not a task), presumably requesting a single node.
2. let the workflow submit tasks, which creates new PBS jobs that requests additional nodes.

I never tried this but with the right `hosts.yml` file, the computing nodes should be able to ssh to headnode and submit jobs, right? What is the problem here?

Also I think the cluster-executing mode was designed to avoid the trouble by

1. submit a workflow, requesting multiple nodes.
2. multiple sos instances are started and the master one will send jobs to the workers.

This would be conceptually easier and more efficient if there are many small substeps.

**Comment by BoPeng** [comment]
If the purpose.is to submit tasks from computing nodes, we may have to

1. On the cluster definition, define both `workflow_template` and `task_template`. The `workflow_template` will be used to execute workflow on computing node, and `task_template` will be needed to submit tasks. 
 
2. On the head node, execute
```
sos run myworkflow -r cluster -q cluster
```
Because `cluster` is defined as a `PBS` queue, the workflow will be submitted using a template (`workflow_template`).

3. Hopefully, the workflow would be executed on computing node as command
```
sos run myworkflow -q cluster
```
which will then submit jobs to the cluster.

These should all in theory work after recent improvement on remote execution (#1418, not yet released). I will create a test case and try it on our cluster.

**Comment by BoPeng** [comment]
It is working. Here is how to reproduce,

1. Under test, run `build_test_docker.sh`, which will start a docker instance and a configuration file `~/docker.yml`, with the following text (port number will vary, and with unrelated hosts removed)

```
localhost: localhost
remote_user: root
hosts:
    localhost:
        description: localhost
        address: localhost
        paths:
            home: /Users/bpeng
    docker:
        address: "{remote_user}@localhost"
        port: 55004
        paths:
            home: "/{remote_user}"
    ts:
        description: task spooler on the docker machine
        based_on: hosts.docker
        queue_type: pbs
        status_check_interval: 5
        task_template: |
            #!/bin/bash
            # {task}
            cd {cur_dir}
            sos execute {task} -v {verbosity} -s {sig_mode} {'--dryrun' if run_mode == 'dryrun' else ''}
        max_running_jobs: 100
        submit_cmd: tsp -L {job_name} sh {job_file}
        status_cmd: tsp -s {job_id}
        kill_cmd: tsp -r {job_id}
        workflow_template: |
            #!/bin/bash
            #
            {command}
```

Note that the cluster (in this case `docker/ts`) needs to have `sos-pbs` installed, so that the tasks could be submitted as a PBS 

2. Have a workflow with a task
```
task:
sh:
   echo this is task.
```


3. Submit the workflow with command
```
sos run test -c ~/docker.yml -r ts -q ts
```

What will happen is that

a. A script will be submitted as a workflow to `docker`

```
#!/bin/bash
#
sos run /root/vatlab/sos/test/test.sos -q ts -c ~/.sos/tmp3xv_vygv.yml
```

b. When the workflow is executed, a second job will be submitted with script

```
#!/bin/bash
# b64cd2a6a63ed501
cd /root
sos execute b64cd2a6a63ed501 -v 2 -s default
```

This example is simple but I suppose the key elements are there.

@gaow Let me know if this scenario helps.

**Comment by pgcudahy** [comment]
I tried running a job using your template as an example on a SLURM cluster, but nothing shows up in `sos status` on my local machine or the cluster. All I can find is 
```
[pgc29@c19n08 ~]$ sacct -j 45256211                                                                                                                                                  
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
45256211     60435cb54+    general pgc29          1     FAILED      1:0 
45256211.ba+      batch            pgc29          1     FAILED      1:0 
45256211.ex+     extern            pgc29          1  COMPLETED      0:0 
```
Where can I get more debug info for these types of jobs if not `sos status`?

**Comment by BoPeng** [comment]
@pgcudahy I got an email notification but did not see your post here.

The remote execution feature is currently not very user friendly because there is no way to check the status and stdout/err of remote workflows. I am aware of the problem (#1420) but do not know how to address it yet.

That said, you can manually check the status by checking the output of the workflow from the output captured by SLURM, and see what went wrong. It is also possible that the job was not submitted correctly due to lack of `WALLTIME` etc, which should be specified from command line.

I will try again today on a PBS system and post a configuration file for a real cluster, and have a harder look at #1420.

**Comment by pgcudahy** [comment]
Thank you. I deleted my post because I'm having some issues with my jobs using both the task queue method I was using before and this new method since upgrading to 0.22.3 and wanted to try and untangle what was specific to this issue.

**Comment by BoPeng** [comment]
I am sorry about that. There have been some changes to the use of named path, basically absolute local paths are no longer translated (#1417), but the change might have introduced other bugs. I will be happy to have a look at your script / configuration if you cannot figure out what caused the problem.

**Comment by BoPeng** [comment]
Just to report my progress.

On a true PBS cluster, I have the definition:

```
host:
  hpc:
    based_on: hosts.cluster
    queue_type: pbs
    status_check_interval: 30
    wait_for_task: false
    modules: []
    max_running_jobs: 500
    submit_cmd: qsub {job_file}
    status_cmd: qstat {job_id}
    kill_cmd: qdel {job_id}
    task_template: |
      #!/bin/bash
      #PBS -N {task}
      #PBS -l nodes={nodes}:ppn={cores}
      #PBS -l walltime={walltime}
      #PBS -l vmem={mem//10**9}GB
      #PBS -o /home/{user_name}/.sos/tasks/{task}.out
      #PBS -e /home/{user_name}/.sos/tasks/{task}.err
      #PBS -m ae
      #PBS -M {user_name}@bcm.edu
      #PBS -v {workdir}

      module load {' '.join(modules)}

      {command}
    workflow_template: |
       #!/bin/bash
       #PBS -N {job_name}
       #PBS -l nodes={nodes}:ppn={cores}
       #PBS -l walltime={walltime}
       #PBS -l vmem={mem}
       #PBS -o /home/{user_name}/.sos/workflows/{job_name}.out
       #PBS -e /home/{user_name}/.sos/workflows/{job_name}.err
       #PBS -m ae
       #PBS -M {user_name}@bcm.edu

       module load {' '.join(modules)}
       {command}
```

From sos notebook with the following workflow

```
%run -q hpc -r hpc mem=2GB cores=1 walltime=00:10:00 nodes=1

input: for_each=dict(i=range(2))
output: f'test_{i}.txt'

task: expand=True, walltime='10m', cores=1, mem='1G'
sh:
    echo `pwd` > {_output}
    echo I am {i} >> {_output}
```

The workflow is correctly submitted to the cluster, which results in a directory `~/.sos/workflows/` and some related files. The `.sh` file is the shell script, the `.err` file is the error.

I got error

```
INFO: Running default:
qsub: Job rejected by all possible destinations (check syntax, queue resources, ...)
WARNING: Check output of qsub ~/.sos/tasks/9e83077913e509c3.sh failed: Command 'qsub ~/.sos/tasks/9e83077913e509c3.sh' returned non-zero exit status 193.
ERROR: Failed to submit task 9e83077913e509c3:
```

And the jobs are pending

```
$ sos status
9e83077913e509c3	86bbadb568b7e0ab default u233771	              	pending
a62dceff0a12a526	86bbadb568b7e0ab default u233771	              	pending
```

The jobs can be submitted manually:

```
$ qsub ~/.sos/tasks/a62dceff0a12a526.sh
2276807.radiation.dldcc.bcm.edu
$ sos status
9e83077913e509c3	86bbadb568b7e0ab default u233771	              	pending
a62dceff0a12a526	86bbadb568b7e0ab default u233771	Ran for 0s    	completed
```

I guess that the `qsub` command is not available on the computing node, but we will see.
