### ISSUE TITLE
Sos flooding cluster login node

### ISSUE THREAD

**Issue by pgcudahy** [vatlab/sos#1424]
Since upgrading to 0.22.4 I've had issues using my HPC cluster. I've kept my hosts.yml file the same, so maybe I need to change it to keep up with the recent changes.

My job is
```
%run snippy-single-end-kraken-hpc -q 'yale_hpc_slurm'

[snippy-single-end-kraken-hpc]
input: remote(single_reads), group_by=1
output: remote(f'/home/pgc29/scratch60/helen_mixed_infection/data/snippy/kraken_filtered/NC_000962/\
{os.path.split(_input[0].resolve())[1].split("_mtb_classified_reads_")[0]}/snps.aligned.fa')
task: walltime='00:45:00', mem='4G', trunk_size=60, trunk_workers=20, 
        workdir='/home/pgc29/scratch60/helen_mixed_infection/data/snippy'
run: expand=True
    module load miniconda
    source activate snippy
    snippy --outdir {_output:d} \
    --se {_input} \
    --ref /home/pgc29/scratch60/helen_mixed_infection/dataraw/NC_000962/NC_000962.3.fasta \
    --mincov 10 \
    --minfrac 0.75 \
    --cpus 1 \
    --cleanup \
    --force
```
And my hosts.yml is 
```
yale_hpc_slurm:
    address: pgc29@xx.xx.xx.xxx
    paths:
      home: /home/pgc29/
      scratch: /home/pgc29/scratch60/
    sos: /home/pgc29/.local/bin/sos
    queue_type: pbs
    status_check_interval: 120
    max_running_jobs: 200
    max_cores: 200
    max_walltime: "72:00:00"
    max_mem: 1200G
    submit_cmd: sbatch {job_file}
    submit_cmd_output: "Submitted batch job {job_id}"
    status_cmd: squeue --job {job_id}
    kill_cmd: scancel {job_id}
    task_template: |
        #!/bin/bash
        #SBATCH --time={walltime}
        #SBATCH --nodes={nodes}
        #SBATCH --ntasks-per-node={cores}
        #SBATCH --mem-per-cpu={mem // cores // 1000000000}G
        #SBATCH --job-name={task}
        #SBATCH --output=/home/pgc29/.sos/tasks/{task}.out
        #SBATCH --error=/home/pgc29/.sos/tasks/{task}.err
        #SBATCH --requeue
        #SBATCH --partition=general,scavenge
        cd {workdir}
        {command}
```
But running this now leads to no output with `sos status` and the cluster login node slows to a crawl. When I run `top` on the cluster I see
```
[pgc29@farnam2 ~]$ top

top - 03:47:34 up 83 days, 17:01, 48 users,  load average: 108.98, 68.53, 32.03
Tasks: 1169 total,   3 running, 1165 sleeping,   1 stopped,   0 zombie
%Cpu(s):  0.4 us,  2.0 sy,  2.3 ni, 91.6 id,  3.7 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 13118614+total, 96860144 free, 23155532 used, 11170472 buff/cache
KiB Swap: 16777212 total, 16334836 free,   442376 used. 10499411+avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                              
 2236 root       0 -20   30.9g  18.6g   1.8g S  10.3 14.9  16069:10 mmfsd                                                                
 4058 pgc29     30  10   42720   3808   1404 S   1.6  0.0   0:00.05 lua                                                                  
 4061 pgc29     30  10   42744   3828   1404 S   1.6  0.0   0:00.05 lua                                                                  
 4083 pgc29     30  10   42856   3916   1404 S   1.6  0.0   0:00.05 lua                                                                  
 4057 pgc29     30  10   43152   4284   1436 D   1.2  0.0   0:00.05 lmod                                                                 
 4060 pgc29     30  10   42744   3828   1404 S   1.2  0.0   0:00.04 lua                                                                  
 4064 pgc29     30  10   42744   3832   1404 S   1.2  0.0   0:00.04 lua                                                                  
 4077 pgc29     30  10   43152   4248   1436 D   1.2  0.0   0:00.04 lmod                                                                 
 4080 pgc29     30  10   42744   3828   1404 D   1.2  0.0   0:00.04 lua                                                                  
 4094 pgc29     30  10   42744   3828   1404 S   1.2  0.0   0:00.04 lua                                                                  
 4123 pgc29     30  10   42748   3820   1404 D   1.2  0.0   0:00.04 lua                                                                  
 4161 pgc29     30  10   42744   3832   1404 D   1.2  0.0   0:00.04 lua                                                                  
 1303 dbus      20   0   79204   2900   1900 S   0.9  0.0  24:10.72 dbus-daemon                                                          
 2855 pgc29     30  10  131636   7384   2808 D   0.9  0.0   0:00.11 conda                                                                
 3085 pgc29     30  10  128692   4704   2572 D   0.9  0.0   0:00.05 conda                                                                
 4072 pgc29     30  10   42724   3820   1404 S   0.9  0.0   0:00.03 lua                                                                  
 4084 pgc29     30  10   42744   3828   1404 S   0.9  0.0   0:00.03 lua                                                                  
 4093 pgc29     30  10   42744   3812   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4095 pgc29     30  10   42744   3828   1404 S   0.9  0.0   0:00.03 lua                                                                  
 4106 pgc29     30  10   42744   3824   1400 D   0.9  0.0   0:00.03 lua                                                                  
 4110 pgc29     30  10   42744   3828   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4117 pgc29     30  10   42744   3832   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4128 pgc29     30  10   42744   3828   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4129 pgc29     30  10   42744   3828   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4136 pgc29     30  10   42744   3828   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4138 pgc29     30  10   42744   3820   1400 D   0.9  0.0   0:00.03 lua                                                                  
 4141 pgc29     30  10   42724   3820   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4142 pgc29     30  10   42744   3832   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4146 pgc29     30  10   42744   3832   1404 D   0.9  0.0   0:00.03 lua                                                                  
 4176 pgc29     30  10   42744   3824   1400 D   0.9  0.0   0:00.03 lua                                                                  
 8793 pgc29     30  10  114328   2700   1352 S   0.9  0.0   0:00.04 bash                                                                 
 9052 pgc29     30  10  114320   2724   1352 S   0.9  0.0   0:00.03 bash                                                                 
30940 pgc29     30  10  138476  11884   2328 D   0.9  0.0   0:00.41 conda                                                                
31555 pgc29     30  10  163220   3792   1848 R   0.9  0.0   0:00.29 top  
```
This setup was working fine previously. Any ideas?
