### ISSUE TITLE
Alternative task_template?

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1531]
Currently for each "cluster" we define a `task_template` with a template for SLURM, PBS etc. The way to specify alternative `task_template` is through the definition of another "cluster". E.g.

```yaml
hosts:
    cluster1:
        task_template
    cluster2:
        based_on: hosts.cluster1
        task_template
```

Or, if the user needs to override some configuraiton, define

```
hosts:
    cluster1:
        task_template
```
in its own `.sos/hosts.yaml` file.

It may be more straightforward to allow multiple templates, such as

```yaml
hosts:
    cluster1:
        task_template:
        multi_node_task-template:
```

but an extra parameter would be needed for the `task` directive.
