### ISSUE TITLE
Enforcement of server restrictions by SoS

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#488]
Our cluster has a no-large-job-on-head-node policy but we will have to use head nodes for all data communications (`rsync`) and job preparation, submission etc.

In practice it is easy to adopt a one-server-multi-config approach like this

```
hosts:
    pbs_head:
        address: cluster_address
        queue_type: process
    pbs:
        address: cluster_address
        queue_type: pbs
        template_file: pbs.tmpl
        ....
```

and use these two queues as follows

```
sos run script rsync_step -q pbs_head
sos run script real_step -q pbs
```

The difference is that task from the first command would be executed directly on head node, and the second command would be submitted to PBS.

The convenience of submitting jobs easily to the cluster also makes it easy to submit the jobs incorrectly. For example,

```
sos run script real_step -q pbs_head
```

would easily slow down or even crash the head node.

I am therefore wondering if there can be some safe guard against this kind of incorrect usage. For example, in the `pbs_head` definition, we could define `walltime` or `mem` or something similar to kill the task if they exceed the limit. This is actually not difficult to do because we can code this in our pulse thread and let the pulse thread kill the job when needed.
