### ISSUE TITLE
Decouple client-server definition to allow more flexible configuration of servers.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#496]
Right now we need to put a localized configuration file for all the machines that we would like to use. This can be inconvenient if we would like to change configuration for a server and error prone because we need to change all entries for all desktops. I would propose that we separate the definition of client and servers that connect them by sos.

**Comment by BoPeng** [comment]
Note that there is no clear definition of server and desktop in this case because we might as well submit jobs on the cluster itself. So in the end we are talking about

```
hosts:
    server1:
           queue_type: pbs
    server2:
           queue_type: rq
           home: /home/myuser
    desktop1:
           home: /Users/myuser
    desktop2:
```

Then if we can make sos know which host it is on, it might be able to figure out all the right `path_map` etc.

**Comment by BoPeng** [comment]
The final piece is that we need to let sos know what server desktop it is on, so before using any of the queue feature, users need to run

```
sos config -g hostname desktop2
```
which will somehow **localize** the `config.yml` file so that it can be used locally. We could also make use of some sort of yaml inclusion magic and define all configurations in `servers.yml` and include it in `config.yml` of all desktops.

**Comment by BoPeng** [comment]
We could allow another configuration file `~/.sos/hosts.yml` to allow separate definition of hosts so that we do not have to mix the configurations with regular `config.yml`.

**Comment by BoPeng** [comment]
I have updated the external task doc to reflect this big design change.

**Comment by BoPeng** [comment]
One of the problem is that YAML's dict is not guaranteed to be ordered, so it is difficult for us to enforce order of keyed elements.

```
    desktop2:
          paths:
               resource: /users/home/resource
               home: /users/home
```
