### ISSUE TITLE
Mandatory server-side configuration.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#555]
#488 has been implemented but it is up to the user to add the restrictions to their `.hosts.yml` file. It is possible to allow system admin to configure the server and enforce certain restrictions. For example, in `/etc/sos.yml`,

```
server_ip:
    process:
        max_mem: 4G
    PBS:
        max_mem: 64G
```

sos could check such file before the task is started.

Note that system admin can enforce the task restrictions manually, by stating `max_mem` etc as policy, and check the tasks with commands such as `sos status task_id -v4 | grep max_mem`.
