### ISSUE TITLE
derived hosts.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#708]
We have had examples of 

```
hosts:
     h1:
        queue: short
        job_template: ... ${queue}
      h2:
        queue: long
        job_template: ... ${queue}
```

so it makes sense to copy definition of a host to another while allowing modification. In this way, the above could be written as

```
hosts:
     h1:
        queue: short
        job_template: ... ${queue}
      h2:
        based_on: h1
        queue: long
```

An additional use of this mechanism is to create alias for a long name. For example, if there are many hosts in `hosts.yml` that are difficult to remember, users could do

```
sos config --global --set hosts.A.based_on a_very_long_name
```
and then `A` could be used as an alias to `a_very_long_name`.

Implementation wise, it can be trouble to handle nested `based_on`, even chained `based_on`.
