### ISSUE TITLE
Behavior when shared and path_map disagree with each other

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#710]
Perhaps it has been correctly handled but I am wondering the behavior of `shared` used in combination with `path_map`.

For example, if `host_A` has

```
paths:
    home: /shared/user 
shared:
    A: /shared
```

and `host_B` has

```
paths:
   home: /home/user
shared:
   A: /scratch/shared
```

So if we following `shared`, if we push `/shared/user/something` to `host_B`, the file would not be copied because is shared, and the destination file would be `/scratch/shared/user/something`.

However, if we follow `paths`, `/shared/user/something` should be mapped to `/home/user/something`. 

It is not entirely clear which map should be used, although `path_map` should override `shared`. Then it seems that the `rsync` command should be changed to a `rsync` command on the remote server from `/scratch/shared/user/something` to `/home/user/something`.
