### ISSUE TITLE
Remote task cur_dir broken?

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#820]
I'm running remote tasks and got this error

```
TRACE: Step becomes task_pending
TRACE: Start submitting M10_986ce4efb43ae3434c72d0d17ab3b9b9 (status: pending)
INFO: M10_986ce4efb43ae3434c72d0d17ab3b9b9 sending [R_library("rhdf5"), ...] (30 items)
ERROR: 'cur_dir'
```

The `v4` info is long but not informative to me. I'll be happy to post more details if the bug cannot be reproduced. My task configuration is:

```
task: workdir = cwd, walltime = '10m', cores = 1, mem = "8G", 
        trunk_size = 200, trunk_workers = 1
```
and I use `${cur_dir}` the same way as [documented here](https://vatlab.github.io/SoS/doc/documentation/Remote_Execution.html)

**Comment by gaow** [comment]
BTW the error persists even if I remove all `${cur_dir}` from my `host.yml` .

**Comment by BoPeng** [comment]
Seems like `cur_dir` is not in the dictionary. Let me see if I can identify the problem without an example.

**Comment by BoPeng** [comment]
Not sure what is going on because `cur_dir` seems to be defined in all relevant environments. Could you send me your site.cfg and scripts or create an example?

**Comment by gaow** [comment]
I was not aware there is a `site.cfg` file! I have a `host.yml` ... is that the reason (that we renamed the config file default name)?

**Comment by BoPeng** [comment]
My typo. There is a sos_site.cfg for system admin though.

**Comment by gaow** [comment]
Great -- I get this MWE:

```
[1]
genes = ["A", "B", "C", "D"]
tissues = [1,2,3,4]
input: for_each = ['genes', 'tissues']
output: "${_tissues}_${_genes!b}.txt"
task: walltime = '10m', cores = 1, mem = "2G", 
        trunk_size = 200, trunk_workers = 1
bash:
 echo hello > ${_output}
```

The key is the loops. I do not think configuration matters but it is here:

```
  midway2:
    description: xxx xxx xxx 
    address: xxx@xxx.uchicago.edu
    paths:
      home: /home/gaow
    queue_type: pbs
    status_check_interval: 120
    max_running_jobs: 30
    max_cores: 40
    max_walltime: "36:00:00"
    max_mem: 64G
    job_template: |
      #!/bin/bash
      #SBATCH --time=${walltime}
      #SBATCH --nodes=1
      #SBATCH --ntasks-per-node=${cores}
      #SBATCH --mem-per-cpu=${mem//10**9}G
      #SBATCH --job-name=${job_name}
      #SBATCH --output=${cur_dir}/.sos/${job_name}.out
      #SBATCH --error=${cur_dir}/.sos/${job_name}.err
      cd ${cur_dir}
      mkdir -p .sos
      sos execute ${task} -v ${verbosity} -s ${sig_mode} ${'--dryrun' if run_mode == 'dryrun' else ''}
    walltime: "06:00:00"
    cores: 20
    mem: 1G
    submit_cmd: sbatch ${job_file}
    submit_cmd_output: "Submitted batch job {job_id}"
    status_cmd: squeue --job ${job_id}
    kill_cmd: scancel ${job_id}

```
