### ISSUE TITLE
Remote task file issue with localhost 

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#823]
This is related to #822 . Let me try to describe it clearly:

My SoS command is:

```
sos run ... -r midway2
```

which first connects to the remote host `midway2` then submit jobs from there. On that remote host I set `localhost` to be the batch job template, which is also called `midway2` in my `hosts.yml` -- you see as resolution to #822  I updated the documentation with the tip that if a remote host  is a batch system one should set `localhost` to the batch system. 

```
hosts:
  office:
    paths:
      home: /home/gaow
      documents: /home/gaow/Documents
  midway2:
    description: UChicago RCC new cluster
    paths:
      home: /home/gaow
```

However I get this error message:

```
ERROR: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/midway2/M10_045531e5f6ccb5d2dcc7cc1a11edcda0.task'
```

As you can perhaps imaging, the task file is in fact here:

```
~/.sos/tasks/localhost/M10_045531e5f6ccb5d2dcc7cc1a11edcda0.task
```

So it indeed was generated yet under the `localhost` folder.

Looks like a simple fix but I do not recall having this problem before, though. Or am I missing something after all?
