### ISSUE TITLE
"process" queue job template problem

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#894]
Separated from #890.

It looks like for "process" queue `based_on` a `PBS` queue, not all variables are available. For example:

```
cd {cur_dir}
module load R/3.4.3
sos execute {task} -v {verbosity} -s {sig_mode}
: name 'verbosity' is not defined
```

I would assume all variables get inherited? My config:

```
  midway2-process:
    based_on: hosts.midway2
    cur_dir: ~/
    queue_type: process
    status_check_interval: 3
    job_template: "cd {cur_dir}\nmodule load R/3.4.3\nsos execute {task} -v {verbosity} -s {sig_mode}"
```
